name: CI/CD Deploy to VPS using Docker

on:
  push:
    branches:
      - main

env:
  # >>> ĐỔI 2 GIÁ TRỊ NÀY CHO PHÙ HỢP VPS CỦA BẠN <<<
  TARGET_DIR: /srv/myapp
  SERVICE_NAME: myapp

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Clean old source code on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            set -e
            # Đảm bảo thư mục cha tồn tại rồi xóa code cũ
            mkdir -p "$(dirname "${TARGET_DIR}")"
            rm -rf "${TARGET_DIR}"

      - name: Copy source code to VPS via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          source: "."
          target: "${{ env.TARGET_DIR }}"   # dùng env thay vì vars
          overwrite: true
          timeout: 1m
          command_timeout: 10m
          rm: false
          debug: false

      - name: SSH into VPS and deploy container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            set -e
            APP_DIR="${TARGET_DIR}"
            SERVICE="${SERVICE_NAME}"

            cd "$APP_DIR"

            # Ghi file .env từ secret
            cat > .env <<EOF
            ${{ secrets.ENV_FILE }}
            EOF

            # Dừng & xóa container cũ nếu có
            docker stop "$SERVICE" 2>/dev/null || true
            docker rm "$SERVICE" 2>/dev/null || true

            # Build lại Docker image
            docker build --no-cache -t "$SERVICE" .

            # Chạy container mới, map port 2609 -> 8080
            docker run -d --name "$SERVICE" --restart unless-stopped -p 2609:8080 --env-file .env "$SERVICE"
