name: CI/CD Deploy to VPS using Docker

on:
  push:
    branches: [ main ]   # nhớ push vào 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      # Kiểm tra biến đầu vào (không in secrets)
      - name: Preflight - check vars
        run: |
          echo "TARGET_DIR=${{ vars.TARGET_DIR }}"
          echo "SERVICE_NAME=${{ vars.SERVICE_NAME }}"
          test -n "${{ secrets.VPS_HOST }}" || (echo "VPS_HOST is empty" && exit 1)
          test -n "${{ secrets.VPS_USER }}" || (echo "VPS_USER is empty" && exit 1)
          test -n "${{ secrets.VPS_PASSWORD }}" || (echo "VPS_PASSWORD is empty" && exit 1)
          test -n "${{ secrets.ENV_FILE }}" || (echo "ENV_FILE is empty" && exit 1)

      # Thử SSH đơn giản để biết có đăng nhập được không
      - name: Sanity SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script_stop: true
          command_timeout: 3m
          debug: true
          script: |
            uname -a
            whoami
            echo "SSH OK"

      - name: Clean old source code on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script_stop: true
          command_timeout: 5m
          script: |
            sudo mkdir -p "${{ vars.TARGET_DIR }}"
            sudo rm -rf "${{ vars.TARGET_DIR }}/*" "${{ vars.TARGET_DIR }}/.??*" || true
            sudo chown -R $USER:$USER "${{ vars.TARGET_DIR }}"

      - name: Copy source code to VPS via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          source: "."
          target: "${{ vars.TARGET_DIR }}"
          overwrite: true
          timeout: 2m
          command_timeout: 10m

      - name: SSH into VPS and deploy container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script_stop: true
          command_timeout: 20m
          script: |
            set -euo pipefail
            APP_DIR="${{ vars.TARGET_DIR }}"
            SERVICE="${{ vars.SERVICE_NAME }}"
            cd "$APP_DIR"

            # Ghi .env từ secret
            cat > .env <<'EOF'
            ${{ secrets.ENV_FILE }}
            EOF
            chmod 600 .env

            # Đảm bảo Docker có mặt
            if ! command -v docker >/dev/null; then
              curl -fsSL https://get.docker.com | sh
            fi

            # Dừng & xóa container cũ (nếu có)
            docker rm -f "$SERVICE" 2>/dev/null || true

            # Build lại image
            docker build --no-cache -t "$SERVICE" .

            # Chạy container, map 1801->8080
            docker run -d --name "$SERVICE" -p 1801:8080 --env-file .env "$SERVICE"

            # Show trạng thái
            docker ps --filter "name=$SERVICE"
            echo "Deployed. Swagger: http://$HOSTNAME:1801/swagger-ui/index.html"
